export const config = Object.freeze({
    githubUrl: "https://github.com/alessandroamella",
    githubDisplayUrl: "github.com/alessandroamella",
    githubUsername: "Alessandro Amella",
    instagramUrl: "https://www.instagram.com/alessandro_amella",
    instagramUsername: "alessandro_amella",
    linkedinUrl: "https://www.linkedin.com/in/alessandro-amella",
    telegramUrl: "https://t.me/alessandroamella",
    telegramDisplayUrl: "t.me/alessandroamella",
    email: "info@bitrey.it",
    recaptchaSiteKey: "6Ley5HsnAAAAAPaw0wALwXFj0FecPxClrHgcMGXL",
    birthday: new Date(2003, 6, 13),
    descriptionNum: 3,
    otherInterestsNum: 4,
    cvAgencies: ["infolog", "seta", "fertec", "freelance"],
    projects: [
        "ezaffitto",
        "vhfesuperiori",
        "occupalostudente",
        "tpldisplay",
        "wolfsurvival",
        "om",
    ],
    languages: ["it", "en", "cs"],
});
