export const config = Object.freeze({
  blogUrl: "https://blog.bitrey.dev",
  githubUrl: "https://github.com/alessandroamella",
  githubDisplayUrl: "github.com/alessandroamella",
  githubUsername: "Alessandro Amella",
  instagramUrl: "https://www.instagram.com/alessandro_amella",
  instagramUsername: "alessandro_amella",
  linkedinUrl: "https://www.linkedin.com/in/alessandro-amella",
  telegramUrl: "https://t.me/alessandroamella",
  telegramDisplayUrl: "t.me/alessandroamella",
  email: "info@bitrey.it",
  recaptchaSiteKey: "6Ley5HsnAAAAAPaw0wALwXFj0FecPxClrHgcMGXL",
  birthday: new Date(2003, 6, 13),
  descriptionNum: 3,
  otherInterestsNum: 4,
  cvAgencies: ["infolog", "seta", "fertec", "freelance"],
  projects: [
    "bamboosim",
    "kinocafe",
    "ezaffitto",
    "vhfesuperiori",
    "occupalostudente",
    "tpldisplay",
    "wolfsurvival",
    "om",
  ],
  languages: [
    {
      value: "it",
      label: "🇮🇹 Italiano",
    },
    {
      value: "en",
      label: "🇬🇧 English",
    },
    {
      value: "cs",
      label: "🇨🇿 Čeština",
    },
  ],
  visitedCountries: [
    { name: "Italy" },
    { name: "Austria" },
    { name: "Germany" },
    { name: "Czech Republic" },
    { name: "Switzerland" },
    { name: "United Kingdom" },
  ],
});
