onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - sharp
  - unrs-resolver

overrides:
  d3-color@<3.1.0: '>=3.1.0'
  nodemailer@<7.0.7: '>=7.0.7'
  nodemailer@<=7.0.10: '>=7.0.11'
