import type { CountryName } from '@/constants/countries-mapping';

export const config = Object.freeze({
  coords: {
    lat: 44.64783,
    lon: 10.92539,
  },
  githubUrl: 'https://github.com/alessandroamella',
  githubDisplayUrl: 'github.com/alessandroamella',
  githubUsername: 'Alessandro Amella',
  instagramUrl: 'https://www.instagram.com/alessandro_amella',
  instagramUsername: 'alessandro_amella',
  linkedinUrl: 'https://www.linkedin.com/in/alessandro-amella',
  qrzUrl: 'https://www.qrz.com/db/IU4QSG',
  birthday: new Date(2003, 6, 13),
  cvAgencies: ['infolog', 'seta', 'fertec', 'freelance'],
  languages: [
    {
      value: 'it',
      label: 'Italiano',
      flag: 'IT',
    },
    {
      value: 'en',
      label: 'English',
      flag: 'EN',
    },
    {
      value: 'cs',
      label: 'Čeština',
      flag: 'CS',
    },
  ],
  visitedCountries: [
    'Albania',
    'Austria',
    'Belgium',
    'Bosnia and Herz.',
    'Bulgaria',
    'Croatia',
    'Czechia',
    'Estonia',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Hungary',
    'Italy',
    'Latvia',
    'Liechtenstein',
    'Lithuania',
    'Malta',
    'Moldova',
    'Netherlands',
    'Poland',
    'Romania',
    'San Marino',
    'Slovakia',
    'Slovenia',
    'Spain',
    'Switzerland',
    'Turkey',
    'Ukraine',
    'United Kingdom',
    'Vatican City',
  ] satisfies CountryName[],
});
