export const config = Object.freeze({
  coords: {
    lat: 44.64783,
    lon: 10.92539,
  },
  blogUrl: 'https://blog.bitrey.dev',
  githubUrl: 'https://github.com/alessandroamella',
  githubDisplayUrl: 'github.com/alessandroamella',
  githubUsername: 'Alessandro Amella',
  instagramUrl: 'https://www.instagram.com/alessandro_amella',
  instagramUsername: 'alessandro_amella',
  linkedinUrl: 'https://www.linkedin.com/in/alessandro-amella',
  telegramUrl: 'https://t.me/alessandroamella',
  telegramDisplayUrl: 't.me/alessandroamella',
  email: 'info@bitrey.it',
  birthday: new Date(2003, 6, 13),
  descriptionNum: 3,
  otherInterestsNum: 4,
  cvAgencies: ['infolog', 'seta', 'fertec', 'freelance'],
  projects: [
    'bamboosim',
    'kinocafe',
    'ezaffitto',
    'vhfesuperiori',
    'occupalostudente',
    'tpldisplay',
    'wolfsurvival',
    'om',
  ],
  languages: [
    {
      value: 'it',
      label: '🇮🇹 Italiano',
    },
    {
      value: 'en',
      label: '🇬🇧 English',
    },
    {
      value: 'cs',
      label: '🇨🇿 Čeština',
    },
  ],
  visitedCountries: [
    { name: 'Albania' },
    { name: 'Austria' },
    { name: 'Bosnia and Herz.' },
    { name: 'Bulgaria' },
    { name: 'Croatia' },
    { name: 'Czechia' },
    { name: 'Estonia' },
    { name: 'Finland' },
    { name: 'France' },
    { name: 'Germany' },
    { name: 'Greece' },
    { name: 'Hungary' },
    { name: 'Italy' },
    { name: 'Latvia' },
    { name: 'Liechtenstein' },
    { name: 'Lithuania' },
    { name: 'Malta' },
    { name: 'Moldova' },
    { name: 'Poland' },
    { name: 'Romania' },
    { name: 'San Marino' },
    { name: 'Slovakia' },
    { name: 'Slovenia' },
    { name: 'Spain' },
    { name: 'Switzerland' },
    { name: 'Ukraine' },
    { name: 'United Kingdom' },
    { name: 'Vatican City' },
  ],
});
