export const config = Object.freeze({
  coords: {
    lat: 44.64783,
    lon: 10.92539,
  },
  blogUrl: 'https://blog.bitrey.dev',
  githubUrl: 'https://github.com/alessandroamella',
  githubDisplayUrl: 'github.com/alessandroamella',
  githubUsername: 'Alessandro Amella',
  instagramUrl: 'https://www.instagram.com/alessandro_amella',
  instagramUsername: 'alessandro_amella',
  linkedinUrl: 'https://www.linkedin.com/in/alessandro-amella',
  telegramUrl: 'https://t.me/alessandroamella',
  telegramDisplayUrl: 't.me/alessandroamella',
  email: 'alessandro@bitrey.dev',
  birthday: new Date(2003, 6, 13),
  otherInterestsNum: 4,
  cvAgencies: ['infolog', 'seta', 'fertec', 'freelance'],
  languages: [
    {
      value: 'it',
      label: 'Italiano',
      flag: 'IT',
    },
    {
      value: 'en',
      label: 'English',
      flag: 'EN',
    },
    {
      value: 'cs',
      label: 'Čeština',
      flag: 'CS',
    },
  ],
  visitedCountries: [
    { name: 'Albania', alpha2: 'AL' },
    { name: 'Austria', alpha2: 'AT' },
    { name: 'Bosnia and Herz.', alpha2: 'BA' },
    { name: 'Bulgaria', alpha2: 'BG' },
    { name: 'Croatia', alpha2: 'HR' },
    { name: 'Czechia', alpha2: 'CZ' },
    { name: 'Estonia', alpha2: 'EE' },
    { name: 'Finland', alpha2: 'FI' },
    { name: 'France', alpha2: 'FR' },
    { name: 'Germany', alpha2: 'DE' },
    { name: 'Greece', alpha2: 'GR' },
    { name: 'Hungary', alpha2: 'HU' },
    { name: 'Italy', alpha2: 'IT' },
    { name: 'Latvia', alpha2: 'LV' },
    { name: 'Liechtenstein', alpha2: 'LI' },
    { name: 'Lithuania', alpha2: 'LT' },
    { name: 'Malta', alpha2: 'MT' },
    { name: 'Moldova', alpha2: 'MD' },
    { name: 'Poland', alpha2: 'PL' },
    { name: 'Romania', alpha2: 'RO' },
    { name: 'San Marino', alpha2: 'SM' },
    { name: 'Slovakia', alpha2: 'SK' },
    { name: 'Slovenia', alpha2: 'SI' },
    { name: 'Spain', alpha2: 'ES' },
    { name: 'Switzerland', alpha2: 'CH' },
    { name: 'Ukraine', alpha2: 'UA' },
    { name: 'United Kingdom', alpha2: 'GB' },
    { name: 'Vatican City', alpha2: 'VA' },
  ],
});
