import type { CountryName } from '@/constants/countries-mapping';

export const config = Object.freeze({
  coords: {
    lat: 56.16287,
    lon: 10.20392,
  },
  githubUrl: 'https://github.com/alessandroamella',
  githubDisplayUrl: 'github.com/alessandroamella',
  githubUsername: 'Alessandro Amella',
  instagramUrl: 'https://www.instagram.com/alessandro_amella',
  instagramUsername: 'alessandro_amella',
  linkedinUrl: 'https://www.linkedin.com/in/alessandro-amella',
  qrzUrl: 'https://www.qrz.com/db/IU4QSG',
  birthday: new Date(2003, 6, 13),
  cvAgencies: ['infolog', 'seta', 'fertec', 'freelance'],
  languages: [
    {
      value: 'it',
      label: 'Italiano',
      flag: 'IT',
      hidden: false,
    },
    {
      value: 'en',
      label: 'English',
      flag: 'EN',
      hidden: false,
    },
    {
      value: 'cs',
      label: 'Čeština',
      flag: 'CS',
      // route still works, just not offered in the language dropdown for now
      hidden: true,
    },
  ],
  visitedCountries: [
    'Albania',
    'Austria',
    'Belgium',
    'Bosnia and Herz.',
    'Bulgaria',
    'Croatia',
    'Czechia',
    'Denmark',
    'Estonia',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Hungary',
    'Italy',
    'Latvia',
    'Liechtenstein',
    'Lithuania',
    'Malta',
    'Moldova',
    'Netherlands',
    'Poland',
    'Romania',
    'San Marino',
    'Slovakia',
    'Slovenia',
    'Spain',
    'Switzerland',
    'Turkey',
    'Ukraine',
    'United Kingdom',
    'Vatican City',
  ] satisfies CountryName[],
});
